### ISSUE TITLE
Comparison webpage broken on safari

### ISSUE THREAD

**Issue by Kiran-Raj-Dev** [kolibril13/flyingframes#21]
[This](https://kolibril13.github.io/mobject-gallery/compare.html) webpage is broken on safari. 
Specifically the columns do not align properly.

<img width="1440" alt="Screenshot 2021-12-03 at 1 40 01 PM" src="https://user-images.githubusercontent.com/90276965/144567962-a7375819-698f-4af3-95d6-b87af1716791.png">

<img width="1440" alt="Screenshot 2021-12-03 at 1 41 09 PM" src="https://user-images.githubusercontent.com/90276965/144568116-6f82da5d-b569-4455-bc6c-a3d7d2df1d67.png">

**Comment by kolibril13** [comment]
Thanks for noting!
This was just a quick draft project for comparing these two to see where the development of OpenGL is right now and where it will go next.
I won't maintain or update the page, so I am closing this issue.
